### ISSUE TITLE
is there a way to save the array-keyed-map as a file?

### ISSUE THREAD

**Issue by azarmadr** [anko/array-keyed-map#6]
NOt an issue.
I am using array-keyed-map in my project. I would like to store my map as a JSON file. and I am writing multiple functions for different akmaps to save them to a file. I am just looking for a uniform way to store the akmap as a file.

thanks

**Comment by anko** [comment]
Ah, I see what you mean now.  A tree structure would be more compact to store.

There's no built-in method to do that currently, because as explained in the readme, normal JS objects are unsuitable for this type of data structure in the general case.  Even if you know your keys are JSON-serialisable, JSON has no `Symbol` keys to guarantee no collisions between data and metadata.

- - -

For now, I'd recommend a transformation like this:

```js
const AKM = require('array-keyed-map')

const original = new AKM()
original.set(['a', 'b'], 'ab')
original.set(['a', 'b', 'c'], 'abc')

const serialised = JSON.stringify(toPlainObject(original))
console.log(serialised)
// => '{"a":{"b":{"__DATA__":"ab","c":{"__DATA__":"abc"}}}}'


const reconstructed = fromPlainObject(JSON.parse(serialised))
console.log([...reconstructed.entries()])
// => [ [ [ 'a', 'b' ], 'ab' ], [ [ 'a', 'b', 'c' ], 'abc' ] ]

//////

function toPlainObject (akmap) {
  const out = {}
  for (const [path, value] of akmap.entries()) {
    setAtPath(out, path, value)
  }
  return out

  function setAtPath (obj, path, value) {
    for (const key of path) obj = obj[key] ??= {}
    obj['__DATA__'] = value
  }
}

function fromPlainObject (obj) {
  const akmap = new AKM()
  for (const [path, value] of allPaths(obj)) {
    akmap.set(path, value)
  }
  return akmap

  function* allPaths(obj, stack = []) {
    for (let [key, value] of Object.entries(obj)) {
      if (key === '__DATA__') yield [stack, value]
      else yield* allPaths(value, stack.concat([key]))
    }
  }
}
```

Replace `'__DATA__'` with whatever string doesn't appear in your actual key paths.

Is that the encoding you were hoping for?

**Comment by azarmadr** [comment]
On point. the `fromPlainObject` is cool. I was struggling with the Object.entries, I had a lot of nested loops with forEach. You created an iterator.

Thanks for your patience.

**Comment by thw0rted** [comment]
Would you consider reopening this to ship a `replacer` and matching `reviver`?  I'm imagining an API like:

```js
import AKM, { replacer, reviver } from "array-keyed-map";

const map = new AKM();
// ...
const VALUE_PLACEHOLDER = "__DATA__";
const str = JSON.serialize(map, replacer(VALUE_PLACEHOLDER))`;
JSON.parse(str, reviver(VALUE_PLACEHOLDER));
```

I use something similar today to (de)serialize ES6 Maps and Sets -- a simple reviver/replacer pair writes out the collection using `Array.from`, with a known string value as the first entry, then checks for that "magic' entry on reviving and returns a Set or Map instead of an array.
